// AuctionPortal.InfrastructureLayer.Infrastructure/InventoryInfrastructure.cs
using AuctionPortal.Common.Infrastructure;
using AuctionPortal.InfrastructureLayer.Interfaces;
using AuctionPortal.Models;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Threading.Tasks;

namespace AuctionPortal.InfrastructureLayer.Infrastructure
{
    public class InventoryInfrastructure : BaseInfrastructure, IInventoryInfrastructure
    {
        #region Constructor
        /// <summary>
        /// InventoryInfrastructure initializes class object.
        /// </summary>
        public InventoryInfrastructure(IConfiguration configuration, ILogger<InventoryInfrastructure> logger)
            : base(configuration, logger)
        {
        }
        #endregion

        #region Constants
        private const string AddStoredProcedureName = "[dbo].[sp_Inventory_Add]";
        private const string ActivateStoredProcedureName = "[dbo].[sp_Inventory_Activate]";
        private const string GetStoredProcedureName = "[dbo].[sp_Inventory_Get]";
        private const string GetListStoredProcedureName = "[dbo].[sp_Inventory_GetAll]";
        private const string UpdateStoredProcedureName = "[dbo].[sp_Inventory_Update]";

        private const string InventoryIdColumnName = "InventoryId";
        private const string ProductIdColumnName = "ProductId";
        private const string ProductJSONColumnName = "ProductJSON";
        private const string DescriptionColumnName = "Description";

        private const string InventoryIdParameterName = "@InventoryId";
        private const string ProductIdParameterName = "@ProductId";
        private const string ProductJSONParameterName = "@ProductJSON"; // not used (server builds JSON)
        private const string DescriptionParameterName = "@Description";
        private const string CreatedByIdParameterName = "@CreatedById";
        private const string ModifiedByIdParameterName = "@ModifiedById";
        #endregion

        #region IInventoryInfrastructure Implementation

        /// <summary>
        /// Add adds new Inventory row and returns generated InventoryId.
        /// ProductJSON is generated by the stored procedure.
        /// </summary>
        public async Task<int> Add(Inventory inventory)
        {
            var parameters = new List<DbParameter>
            {
                base.GetParameter(ProductIdParameterName, inventory.ProductId),
                base.GetParameter(DescriptionParameterName, (object?)inventory.Description ?? DBNull.Value),
                base.GetParameter(CreatedByIdParameterName, inventory.CreatedById)
            };

            // sp_Inventory_Add INSERTs and SELECTs the inserted row.
            using (var reader = await base.ExecuteReader(parameters, AddStoredProcedureName, CommandType.StoredProcedure))
            {
                if (reader != null && reader.HasRows && reader.Read())
                {
                    inventory.InventoryId = reader.GetIntegerValue(InventoryIdColumnName);
                    inventory.ProductId = reader.GetIntegerValue(ProductIdColumnName);
                    inventory.ProductJSON = reader.GetStringValue(ProductJSONColumnName);
                    inventory.Description = reader.GetStringValue(DescriptionColumnName);

                    // Audit
                    inventory.CreatedById = reader.GetIntegerValueNullable(BaseInfrastructure.CreatedByIdColumnName);
                    inventory.CreatedDate = reader.GetDateTimeValueNullable(BaseInfrastructure.CreatedDateColumnName);
                    inventory.ModifiedById = reader.GetIntegerValueNullable(BaseInfrastructure.ModifiedByIdColumnName) ?? 0;
                    inventory.ModifiedDate = reader.GetDateTimeValueNullable(BaseInfrastructure.ModifiedDateColumnName);
                    inventory.Active = reader.GetBooleanValue(BaseInfrastructure.ActiveColumnName);
                }

                if (reader != null && !reader.IsClosed)
                    reader.Close();
            }

            return inventory.InventoryId;
        }

        /// <summary>
        /// Activate activate/deactivate provided record and returns true if successful.
        /// </summary>
        public async Task<bool> Activate(Inventory inventory)
        {
            var parameters = new List<DbParameter>
            {
                base.GetParameter(InventoryIdParameterName, inventory.InventoryId),
                base.GetParameter(BaseInfrastructure.ActiveParameterName, inventory.Active),
                base.GetParameter(ModifiedByIdParameterName, inventory.ModifiedById)
            };

            var rows = await base.ExecuteNonQuery(parameters, ActivateStoredProcedureName, CommandType.StoredProcedure);
            return rows > 0;
        }

        /// <summary>
        /// Get fetches and returns a single Inventory.
        /// </summary>
        public async Task<Inventory> Get(Inventory inventory)
        {
            Inventory item = null;

            var parameters = new List<DbParameter>
            {
                base.GetParameter(InventoryIdParameterName, inventory.InventoryId)
            };

            using (var reader = await base.ExecuteReader(parameters, GetStoredProcedureName, CommandType.StoredProcedure))
            {
                if (reader != null && reader.HasRows && reader.Read())
                {
                    item = new Inventory
                    {
                        InventoryId = reader.GetIntegerValue(InventoryIdColumnName),
                        ProductId = reader.GetIntegerValue(ProductIdColumnName),
                        ProductJSON = reader.GetStringValue(ProductJSONColumnName),
                        Description = reader.GetStringValue(DescriptionColumnName),

                        CreatedById = reader.GetIntegerValueNullable(BaseInfrastructure.CreatedByIdColumnName),
                        CreatedDate = reader.GetDateTimeValueNullable(BaseInfrastructure.CreatedDateColumnName),
                        ModifiedById = reader.GetIntegerValueNullable(BaseInfrastructure.ModifiedByIdColumnName) ?? 0,
                        ModifiedDate = reader.GetDateTimeValueNullable(BaseInfrastructure.ModifiedDateColumnName),
                        Active = reader.GetBooleanValue(BaseInfrastructure.ActiveColumnName)
                    };
                }

                if (reader != null && !reader.IsClosed)
                    reader.Close();
            }

            return item;
        }

        /// <summary>
        /// GetList fetches and returns a list of Inventory (trimmed columns).
        /// </summary>
        public async Task<List<Inventory>> GetList(Inventory inventory)
        {
            var items = new List<Inventory>();
            var parameters = new List<DbParameter>(); // none

            using (var reader = await base.ExecuteReader(parameters, GetListStoredProcedureName, CommandType.StoredProcedure))
            {
                if (reader != null)
                {
                    while (reader.Read())
                    {
                        var item = new Inventory
                        {
                            InventoryId = reader.GetIntegerValue(InventoryIdColumnName),
                            ProductId = reader.GetIntegerValue(ProductIdColumnName),
                            ProductJSON = reader.GetStringValue(ProductJSONColumnName),
                            Description = reader.GetStringValue(DescriptionColumnName),
                            Active = reader.GetBooleanValue(BaseInfrastructure.ActiveColumnName)
                        };

                        items.Add(item);
                    }

                    if (!reader.IsClosed)
                        reader.Close();
                }
            }

            return items;
        }

        /// <summary>
        /// Update updates an existing Inventory and returns true if successful.
        /// ProductJSON is rebuilt by the stored procedure when ProductId changes (or kept in sync).
        /// </summary>
        public async Task<bool> Update(Inventory inventory)
        {
            var parameters = new List<DbParameter>
            {
                base.GetParameter(InventoryIdParameterName, inventory.InventoryId),

                // pass NULLs when not changing (server will COALESCE to existing)
                base.GetParameter(ProductIdParameterName, inventory.ProductId > 0 ? (object)inventory.ProductId : DBNull.Value),
                base.GetParameter(DescriptionParameterName, (object?)inventory.Description ?? DBNull.Value),

                base.GetParameter(ModifiedByIdParameterName, inventory.ModifiedById)
            };

            var rows = await base.ExecuteNonQuery(parameters, UpdateStoredProcedureName, CommandType.StoredProcedure);
            return rows > 0;
        }

        #endregion
    }
}
